{{-- resources/views/projects/report.blade.php --}}
@extends('layouts.app')

@section('title', 'Project Report — ' . $project->name)

@section('content')

{{-- ============================================================ --}}
{{-- SCREEN-ONLY TOOLBAR (hidden in print)                        --}}
{{-- ============================================================ --}}
<div class="no-print max-w-5xl mx-auto px-4 pt-6">
    <div class="flex flex-wrap items-center justify-between gap-3">
        <a href="{{ route('projects.show', $project) }}" class="text-sm text-gray-500 hover:text-gray-700 inline-flex items-center gap-1">
            <i class="fas fa-arrow-left"></i> Back to project
        </a>
        <div class="flex items-center gap-2">
            @if($project->status !== 'completed' && $isPrincipal)
                <span class="text-xs px-3 py-1.5 bg-amber-50 text-amber-700 rounded-full">
                    <i class="fas fa-info-circle mr-1"></i> Live snapshot — project not completed
                </span>
            @endif
            <button onclick="window.print()"
                    class="px-4 py-2 bg-[#1a2a4a] hover:bg-[#0f1a30] text-white text-sm font-medium rounded-lg transition inline-flex items-center gap-2">
                <i class="fas fa-print"></i> Print / Save as PDF
            </button>
        </div>
    </div>
</div>

{{-- ============================================================ --}}
{{-- REPORT DOCUMENT                                              --}}
{{-- ============================================================ --}}
<article id="report-document" class="max-w-5xl mx-auto px-4 py-6 print:max-w-none print:px-0 print:py-0">

    {{-- ============================================================ --}}
    {{-- COVER PAGE                                                  --}}
    {{-- ============================================================ --}}
    <section class="report-cover">
        <div class="cover-inner">
            <div class="cover-brand">
                <div class="cover-logo">EqualFlow</div>
                <div class="cover-tagline">Project Completion Report</div>
            </div>

            <div class="cover-main">
                <h1 class="cover-title">{{ $project->name }}</h1>

                @if($project->description)
                    <p class="cover-description">{{ $project->description }}</p>
                @endif

                <table class="cover-meta">
                    <tbody>
                        @if($project->organization)
                            <tr>
                                <td class="meta-label">Organization</td>
                                <td class="meta-value">{{ $project->organization->name }}</td>
                            </tr>
                        @endif
                        @if($project->creator)
                            <tr>
                                <td class="meta-label">Created By</td>
                                <td class="meta-value">{{ $project->creator->name }}</td>
                            </tr>
                        @endif
                        @if($project->start_date)
                            <tr>
                                <td class="meta-label">Start Date</td>
                                <td class="meta-value">{{ $project->start_date->format('d F Y') }}</td>
                            </tr>
                        @endif
                        @if($project->deadline)
                            <tr>
                                <td class="meta-label">Deadline</td>
                                <td class="meta-value">{{ $project->deadline->format('d F Y') }}</td>
                            </tr>
                        @endif
                        <tr>
                            <td class="meta-label">Status</td>
                            <td class="meta-value">{{ ucfirst(str_replace('_', ' ', $project->status)) }}</td>
                        </tr>
                        <tr>
                            <td class="meta-label">Report Date</td>
                            <td class="meta-value">{{ now()->format('d F Y, H:i') }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="cover-footer">
                <p>Generated by EqualFlow · Document ID: {{ strtoupper(substr(md5($project->id . $project->name), 0, 8)) }}</p>
            </div>
        </div>
    </section>

    {{-- ============================================================ --}}
    {{-- TABLE OF CONTENTS (auto-numbered, no page numbers)          --}}
    {{-- ============================================================ --}}
    <section class="report-section report-toc">
        <h2 class="section-title">Contents</h2>
        <ol class="toc-list">
            <li>Overview</li>
            @if($contributors->count())
                <li>Contributors ({{ $contributors->count() }})</li>
            @endif
            @if($deptStats->count())
                <li>Progress by Department</li>
            @endif
            <li>Task Register</li>
            @if($project->documents->count())
                <li>Project Documents ({{ $project->documents->count() }})</li>
            @endif
            @if($timeline->count())
                <li>Activity Timeline ({{ $timeline->count() }} events)</li>
            @endif
        </ol>
    </section>

    {{-- ============================================================ --}}
    {{-- 1. OVERVIEW                                                 --}}
    {{-- ============================================================ --}}
    <section class="report-section page-break">
        <h2 class="section-title">1. Overview</h2>

        <div class="stat-grid">
            <div class="stat-cell">
                <div class="stat-value">{{ $stats['total_main_tasks'] }}</div>
                <div class="stat-label">Main Tasks</div>
            </div>
            <div class="stat-cell">
                <div class="stat-value">{{ $stats['completed_main_tasks'] }}</div>
                <div class="stat-label">Completed</div>
            </div>
            <div class="stat-cell">
                <div class="stat-value">{{ $stats['total_sub_tasks'] }}</div>
                <div class="stat-label">Sub-tasks</div>
            </div>
            <div class="stat-cell">
                <div class="stat-value">{{ $stats['completed_sub_tasks'] }}</div>
                <div class="stat-label">Sub-tasks Done</div>
            </div>
            <div class="stat-cell">
                <div class="stat-value">{{ $stats['total_submissions'] }}</div>
                <div class="stat-label">Submissions</div>
            </div>
            <div class="stat-cell">
                <div class="stat-value">{{ $stats['documents_count'] }}</div>
                <div class="stat-label">Documents</div>
            </div>
        </div>
    </section>

    {{-- ============================================================ --}}
    {{-- 2. CONTRIBUTORS                                             --}}
    {{-- ============================================================ --}}
    @if($contributors->count())
        <section class="report-section">
            <h2 class="section-title">2. Contributors</h2>
            <table class="report-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Job Scope</th>
                        <th>Department</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($contributors as $c)
                        <tr>
                            <td>{{ $c->name }}</td>
                            <td>{{ $c->getJobScopeLabel() ?? '—' }}</td>
                            <td>{{ $c->department?->name ?? '—' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </section>
    @endif

    {{-- ============================================================ --}}
    {{-- 3. DEPARTMENT PROGRESS                                      --}}
    {{-- ============================================================ --}}
    @if($deptStats->count())
        <section class="report-section">
            <h2 class="section-title">3. Progress by Department</h2>
            <table class="report-table">
                <thead>
                    <tr>
                        <th>Department</th>
                        <th class="text-right">Completed</th>
                        <th class="text-right">Total</th>
                        <th class="text-right">Progress</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($deptStats as $d)
                        @php $pct = $d['total'] > 0 ? round(($d['done'] / $d['total']) * 100) : 0; @endphp
                        <tr>
                            <td>{{ $d['name'] }}</td>
                            <td class="text-right">{{ $d['done'] }}</td>
                            <td class="text-right">{{ $d['total'] }}</td>
                            <td class="text-right">
                                <div class="progress-cell">
                                    <div class="progress-track">
                                        <div class="progress-fill" style="width: {{ $pct }}%"></div>
                                    </div>
                                    <span class="progress-pct">{{ $pct }}%</span>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </section>
    @endif

    {{-- ============================================================ --}}
    {{-- 4. TASK REGISTER                                            --}}
    {{-- ============================================================ --}}
    <section class="report-section page-break">
        <h2 class="section-title">4. Task Register</h2>

        @forelse($mainTasks as $main)
            <div class="task-block">
                <div class="task-header">
                    <div>
                        <h3 class="task-title">{{ $main->title }}</h3>
                        <p class="task-meta">
                            {{ $main->department?->name ?? 'Standalone' }}
                            ·
                            Leader: {{ $main->assignee?->name ?? '—' }}
                            @if($main->due_date)
                                · Due {{ $main->due_date->format('d M Y') }}
                            @endif
                        </p>
                    </div>
                    <span class="badge badge-{{ $main->status === 'done' ? 'green' : 'gray' }}">
                        {{ ucfirst(str_replace('_', ' ', $main->status)) }}
                    </span>
                </div>

                @if($main->subtasks->count())
                    <table class="report-table compact">
                        <thead>
                            <tr>
                                <th>Sub-task</th>
                                <th>Assigned To</th>
                                <th>Status</th>
                                <th class="text-right">Versions</th>
                                <th class="text-right">Approved</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($main->subtasks as $sub)
                                @php
                                    $versions = $sub->submissions->pluck('version')->unique()->count();
                                    $approved = $sub->submissions->where('status', 'approved')->count();
                                @endphp
                                <tr>
                                    <td>{{ $sub->title }}</td>
                                    <td>{{ $sub->assignee?->name ?? '—' }}</td>
                                    <td>
                                        <span class="badge badge-{{ $sub->status === 'done' ? 'green' : 'gray' }}">
                                            {{ ucfirst(str_replace('_', ' ', $sub->status)) }}
                                        </span>
                                    </td>
                                    <td class="text-right">{{ $versions }}</td>
                                    <td class="text-right">{{ $approved }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                @else
                    <p class="muted">No sub-tasks.</p>
                @endif
            </div>
        @empty
            <p class="muted text-center">No main tasks.</p>
        @endforelse
    </section>

    {{-- ============================================================ --}}
    {{-- 5. PROJECT DOCUMENTS                                        --}}
    {{-- ============================================================ --}}
    @if($project->documents->count())
        <section class="report-section">
            <h2 class="section-title">5. Project Documents</h2>
            <table class="report-table">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>File</th>
                        <th class="text-right">Size</th>
                        <th>Uploaded By</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($project->documents as $doc)
                        <tr>
                            <td>{{ $doc->title }}</td>
                            <td class="mono">{{ $doc->file_name }}</td>
                            <td class="text-right">{{ $doc->getFileSizeFormatted() }}</td>
                            <td>{{ $doc->uploader?->name }}</td>
                            <td>{{ $doc->created_at->format('d M Y') }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </section>
    @endif

    {{-- ============================================================ --}}
    {{-- 6. ACTIVITY TIMELINE                                        --}}
    {{-- ============================================================ --}}
    @if($timeline->count())
        <section class="report-section">
            <h2 class="section-title">6. Activity Timeline</h2>
            <table class="report-table">
                <thead>
                    <tr>
                        <th style="width: 140px;">Date</th>
                        <th>Activity</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($timeline as $event)
                        <tr>
                            <td class="mono">{{ $event['date']?->format('d M Y H:i') }}</td>
                            <td>
                                <strong>{{ $event['user']?->name ?? 'Unknown' }}</strong>
                                submitted <em>{{ $event['task'] }}</em>
                                @if($event['status'] === 'approved')
                                    — approved by <strong>{{ $event['reviewed_by']?->name }}</strong>
                                @elseif($event['status'] === 'revision_requested')
                                    — revision requested
                                @elseif($event['status'] === 'rejected')
                                    — rejected
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </section>
    @endif

    {{-- ============================================================ --}}
    {{-- DOCUMENT FOOTER                                             --}}
    {{-- ============================================================ --}}
    <footer class="report-footer">
        <div class="footer-line"></div>
        <p class="footer-text">
            <strong>{{ $project->name }}</strong>
            @if($project->organization)
                · {{ $project->organization->name }}
            @endif
            · Report generated {{ now()->format('d F Y, H:i') }}
        </p>
        <p class="footer-text muted">
            End of report.
        </p>
    </footer>
</article>

{{-- ============================================================ --}}
{{-- SCREEN + PRINT STYLES                                        --}}
{{-- ============================================================ --}}
<style>
/* ============================================ */
/* SCREEN STYLES                                */
/* ============================================ */
.report-cover,
.report-section,
.report-footer {
    background: #fff;
    border: 1px solid #e5e7eb;
    border-radius: 1rem;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
    padding: 2rem;
    margin-bottom: 1.5rem;
}

.cover-inner {
    display: flex;
    flex-direction: column;
    min-height: 400px;
    gap: 2rem;
}

.cover-brand {
    display: flex;
    align-items: baseline;
    gap: 0.75rem;
}
.cover-logo {
    font-size: 1.75rem;
    font-weight: 800;
    color: #1a2a4a;
    letter-spacing: -0.02em;
}
.cover-tagline {
    font-size: 0.85rem;
    color: #6b7280;
    text-transform: uppercase;
    letter-spacing: 0.1em;
}

.cover-main {
    flex: 1;
    display: flex;
    flex-direction: column;
    justify-content: center;
}
.cover-title {
    font-size: 2.5rem;
    font-weight: 800;
    color: #1a2a4a;
    line-height: 1.15;
    margin: 0 0 1rem;
    letter-spacing: -0.02em;
}
.cover-description {
    font-size: 1.05rem;
    color: #4b5563;
    line-height: 1.6;
    max-width: 42rem;
    margin: 0 0 2rem;
}

.cover-meta {
    width: 100%;
    max-width: 32rem;
    border-collapse: collapse;
    font-size: 0.9rem;
}
.cover-meta tr {
    border-bottom: 1px solid #f3f4f6;
}
.cover-meta tr:last-child {
    border-bottom: none;
}
.cover-meta .meta-label {
    padding: 0.5rem 1rem 0.5rem 0;
    color: #6b7280;
    font-weight: 500;
    width: 40%;
}
.cover-meta .meta-value {
    padding: 0.5rem 0;
    color: #111827;
    font-weight: 600;
}

.cover-footer {
    text-align: center;
    color: #9ca3af;
    font-size: 0.75rem;
    border-top: 1px solid #f3f4f6;
    padding-top: 1rem;
}

/* TOC */
.report-toc .toc-list {
    list-style: none;
    padding: 0;
    margin: 0;
    counter-reset: toc;
}
.report-toc .toc-list li {
    padding: 0.5rem 0;
    border-bottom: 1px dashed #e5e7eb;
    color: #374151;
    font-size: 0.95rem;
    counter-increment: toc;
    display: flex;
    align-items: center;
    gap: 0.75rem;
}
.report-toc .toc-list li::before {
    content: counter(toc) ".";
    color: #9ca3af;
    font-weight: 600;
    min-width: 1.75rem;
}
.report-toc .toc-list li:last-child {
    border-bottom: none;
}

/* Section titles */
.section-title {
    font-size: 1.35rem;
    font-weight: 700;
    color: #1a2a4a;
    margin: 0 0 1.25rem;
    padding-bottom: 0.5rem;
    border-bottom: 2px solid #1a2a4a;
    letter-spacing: -0.01em;
}

/* Stat grid */
.stat-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 1rem;
}
.stat-cell {
    text-align: center;
    padding: 1.25rem 0.75rem;
    background: #f8fafc;
    border: 1px solid #e5e7eb;
    border-radius: 0.75rem;
}
.stat-value {
    font-size: 2rem;
    font-weight: 800;
    color: #1a2a4a;
    line-height: 1;
}
.stat-label {
    font-size: 0.75rem;
    color: #6b7280;
    margin-top: 0.5rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
}

/* Report tables */
.report-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.875rem;
}
.report-table.compact {
    font-size: 0.8rem;
    margin-top: 0.5rem;
}
.report-table thead th {
    text-align: left;
    font-weight: 600;
    color: #6b7280;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    font-size: 0.7rem;
    padding: 0.5rem 0.75rem;
    border-bottom: 2px solid #e5e7eb;
}
.report-table tbody td {
    padding: 0.6rem 0.75rem;
    border-bottom: 1px solid #f3f4f6;
    color: #374151;
    vertical-align: top;
}
.report-table tbody tr:last-child td {
    border-bottom: none;
}
.text-right { text-align: right; }
.mono {
    font-family: 'Courier New', monospace;
    font-size: 0.78rem;
    color: #4b5563;
}

/* Task blocks */
.task-block {
    margin-bottom: 1.75rem;
    padding-bottom: 1.75rem;
    border-bottom: 1px solid #e5e7eb;
}
.task-block:last-child {
    border-bottom: none;
    padding-bottom: 0;
    margin-bottom: 0;
}
.task-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 1rem;
    margin-bottom: 0.75rem;
}
.task-title {
    font-size: 1rem;
    font-weight: 700;
    color: #1a2a4a;
    margin: 0 0 0.25rem;
}
.task-meta {
    font-size: 0.75rem;
    color: #6b7280;
    margin: 0;
}

/* Badges */
.badge {
    display: inline-block;
    padding: 0.15rem 0.55rem;
    border-radius: 9999px;
    font-size: 0.65rem;
    font-weight: 600;
    text-transform: capitalize;
}
.badge-green { background: #d1fae5; color: #065f46; }
.badge-gray  { background: #f3f4f6; color: #4b5563; }

/* Progress cells */
.progress-cell {
    display: flex;
    align-items: center;
    justify-content: flex-end;
    gap: 0.5rem;
}
.progress-track {
    width: 80px;
    height: 6px;
    background: #f3f4f6;
    border-radius: 9999px;
    overflow: hidden;
}
.progress-fill {
    height: 100%;
    background: linear-gradient(90deg, #34d399, #059669);
    border-radius: 9999px;
}
.progress-pct {
    font-weight: 600;
    color: #374151;
    min-width: 2.5rem;
    text-align: right;
}

/* Footer */
.report-footer {
    text-align: center;
    padding: 1.5rem 2rem;
}
.footer-line {
    height: 2px;
    background: linear-gradient(90deg, transparent, #1a2a4a, transparent);
    margin-bottom: 1rem;
}
.footer-text {
    font-size: 0.75rem;
    color: #6b7280;
    margin: 0.25rem 0;
}
.muted {
    color: #9ca3af;
    font-size: 0.85rem;
}

/* ============================================ */
/* PRINT STYLES — TURN THIS INTO A PROPER REPORT */
/* ============================================ */
@media print {
    /* Page setup */
    @page {
        size: A4 portrait;
        margin: 18mm 16mm 20mm 16mm;
    }

    /* Reset body & main */
    html, body {
        background: #fff !important;
        color: #000 !important;
        font-size: 10.5pt !important;
        line-height: 1.5 !important;
    }

    /* Hide app chrome */
    aside, nav, header, .no-print, .print\:hidden {
        display: none !important;
    }

    main {
        padding: 0 !important;
        margin: 0 !important;
        background: #fff !important;
    }

    /* Report container fills the page */
    #report-document {
        max-width: none !important;
        padding: 0 !important;
        margin: 0 !important;
        background: #fff !important;
    }

    /* Strip card chrome from sections */
    .report-cover,
    .report-section,
    .report-footer {
        background: transparent !important;
        border: none !important;
        box-shadow: none !important;
        border-radius: 0 !important;
        padding: 0 !important;
        margin: 0 0 1.5cm 0 !important;
    }

    /* Cover page — full A4 height, centered */
    .report-cover {
        page-break-after: always;
        break-after: page;
        min-height: calc(297mm - 38mm);
        display: flex;
        flex-direction: column;
    }
    .cover-inner {
        min-height: auto;
        flex: 1;
        justify-content: space-between;
    }
    .cover-title {
        font-size: 28pt !important;
        color: #000 !important;
    }
    .cover-logo {
        font-size: 20pt !important;
        color: #000 !important;
    }
    .cover-description {
        font-size: 12pt !important;
        color: #333 !important;
    }
    .cover-meta {
        font-size: 11pt !important;
    }
    .cover-meta .meta-label {
        color: #555 !important;
    }
    .cover-meta .meta-value {
        color: #000 !important;
    }
    .cover-footer {
        color: #777 !important;
        border-top: 1px solid #999 !important;
    }

    /* TOC — no page break after, but always start a fresh page for content */
    .report-toc {
        page-break-after: always;
        break-after: page;
    }
    .report-toc .toc-list li {
        border-bottom-color: #ccc !important;
    }

    /* Force page breaks before major sections */
    .report-section.page-break {
        page-break-before: always;
        break-before: page;
    }

    /* Prevent splits inside small blocks */
    .task-block,
    .stat-cell,
    .cover-meta tr,
    .report-table tr {
        page-break-inside: avoid;
        break-inside: avoid;
    }

    /* Section titles as document headings */
    .section-title {
        font-size: 14pt !important;
        color: #000 !important;
        border-bottom: 1pt solid #000 !important;
        padding-bottom: 2mm !important;
        margin-bottom: 4mm !important;
        page-break-after: avoid;
        break-after: avoid;
    }

    /* Stats */
    .stat-grid {
        grid-template-columns: repeat(3, 1fr) !important;
        gap: 3mm !important;
    }
    .stat-cell {
        background: #f5f5f5 !important;
        border: 1pt solid #999 !important;
        border-radius: 0 !important;
        padding: 3mm !important;
    }
    .stat-value {
        font-size: 18pt !important;
        color: #000 !important;
    }
    .stat-label {
        color: #444 !important;
        font-size: 8pt !important;
    }

    /* Tables look like a report, not a web table */
    .report-table {
        font-size: 9.5pt !important;
        border-collapse: collapse !important;
    }
    .report-table thead th {
        color: #000 !important;
        border-bottom: 1.5pt solid #000 !important;
        font-size: 8pt !important;
        padding: 2mm 2.5mm !important;
    }
    .report-table tbody td {
        padding: 2mm 2.5mm !important;
        border-bottom: 0.5pt solid #ccc !important;
        color: #000 !important;
    }

    /* Task blocks */
    .task-block {
        border-bottom: 0.5pt solid #ddd !important;
        margin-bottom: 5mm !important;
        padding-bottom: 5mm !important;
    }
    .task-title {
        font-size: 11pt !important;
        color: #000 !important;
    }
    .task-meta {
        color: #555 !important;
        font-size: 9pt !important;
    }

    /* Badges → simple bordered pills */
    .badge {
        background: transparent !important;
        color: #000 !important;
        border: 0.5pt solid #000 !important;
        padding: 0.5mm 2mm !important;
        font-size: 8pt !important;
    }

    /* Progress bars — make them visible but monochrome */
    .progress-track {
        background: #e5e5e5 !important;
        border: 0.5pt solid #999 !important;
    }
    .progress-fill {
        background: #000 !important;
    }
    .progress-pct {
        color: #000 !important;
    }

    /* Footer at the bottom of the last page */
    .report-footer {
        page-break-inside: avoid;
        border-top: 1pt solid #000 !important;
        padding-top: 3mm !important;
    }
    .footer-line {
        display: none;
    }
    .footer-text {
        color: #444 !important;
        font-size: 8.5pt !important;
    }

    /* Links: no underline, no blue */
    a {
        color: #000 !important;
        text-decoration: none !important;
    }

    /* Kill any remaining shadows/radii */
    * {
        box-shadow: none !important;
        text-shadow: none !important;
    }

    /* Add a running header on every page except the first (cover) */
    .report-section,
    .report-toc {
        /* Browsers don't support per-page headers via CSS, but this
           ensures content respects the top margin of @page */
    }

    /* Print column: ensure no two-column layouts remain */
    .grid, [class*="grid-cols-"] {
        display: block !important;
    }
    .grid > *, [class*="grid-cols-"] > * {
        margin-bottom: 3mm !important;
    }
}
</style>

@endsection